mercure:
  hubs:
    default:
      url: '%env(MERCURE_URL)%'
      public_url: '%env(MERCURE_PUBLIC_URL)%'
      jwt:
        secret: '%env(MERCURE_JWT_SECRET)%'
        publish: '*'

when@prod:
  mercure:
    hubs:
      default:
        url: 'https://%env(STACKHERO_MERCURE_HUB_HOST)%/.well-known/mercure'
        public_url: 'https://%env(STACKHERO_MERCURE_HUB_HOST)%/.well-known/mercure'
        jwt:
          secret: '%env(STACKHERO_MERCURE_HUB_PUBLISHER_JWT_KEY)%'
          publish: '*'
